require.config({
	'baseUrl' 					: '/',
	'config'						: {
		'babel' 					: { 'sourceMaps' : 'inline', 'fileExtension' : '.jsx' }   ,
	},
	'waitSeconds'				: 7																												,
	'urlArgs'						: 'v=' + new Date().getTime()														, 	// No caching option.
	'paths'							: {
		'spin'						: '/bower_components/spin.js/spin'												,
		'react'						: '/bower_components/react/react-with-addons'							,
		'reactdom'				: '/bower_components/react/react-dom'											,
		'babel'						: '/bower_components/requirejs-react-jsx/babel-5.8.34.min',
		'jsx'							: '/bower_components/requirejs-react-jsx/jsx'							,
		'text'						: '/bower_components/requirejs-text/text'									,
		'html2Canvas'			: '/bower_components/html2canvas/build/html2canvas.min'		,
		'pdfmake'					: '/bower_components/pdfmake/build/pdfmake'						,
		'vfs_fonts'				: '/bower_components/pdfmake/build/vfs_fonts'							,
		'toHTML'					: '/js/chart/toHTML' 																					,
		'pdf'							: '/js/chart/pdf'																							,
		'sizing'					: '/js/chart/sizing'																					,
		'canvasContext'		: '/js/chart/canvasContext'																		,
		'legend'					: '/js/chart/legend' 																					,
		'format'					: '/js/chart/format' 																					,
		'tooltip'					: '/js/chart/tooltip'																					,
		'loading'					: '/js/chart/loading'																					,
		'sortHandler'			: '/js/population/comutationplot/sortHandler'									,
		'mouseHandler'		: '/js/population/comutationplot/mouseHandler'								,
		'title'						: '/js/population/comutationplot/title'												,
		'comutation'			: '/js/population/comutationplot/comutation'									,
		'mutation'				: '/js/population/comutationplot/mutation'										,
		'patient'					: '/js/population/comutationplot/patient'											,
		'sample'					: '/js/population/comutationplot/sample'											,
		'group'						: '/js/population/comutationplot/group'												,
		'gene'						: '/js/population/comutationplot/gene'												,
		'scale'						: '/js/population/comutationplot/scale'												,
		'pq'							: '/js/population/comutationplot/pq'													,
		'needle'					: '/js/analysis/needleplot/needle'														,
		'navi'						: '/js/analysis/needleplot/navi'															,
		'needleplot'			: '/js/analysis/needleplot/needleplot'												,
		'navigator'				: '/js/analysis/needleplot/navigator'													,
		'pathway'					: '/js/analysis/pathwayplot/pathway'													,
		'expressions'			: '/js/analysis/expressions/expressions'											,
		'expressionPlot'  : '/js/analysis/expressions/expressionPlot'									  ,
		'waterfall'				: '/js/analysis/expressions/waterfall'												,
		'scatter'					: '/js/analysis/expressions/scatter'													,
		'heatmap'					: '/js/analysis/expressions/heatmap'													,
		'options'					: '/js/analysis/expressions/options'													,
	},
	'shims' 						: {
		'spin'						: { 'exports' : 'spin'		  	 	 },
		'react'						: { 'exports' : 'react'		  	 	 },
		'reactdom'				: { 'exports' : 'reactdom'		 	 },
		'toHTML'					: { 'exports' : 'toHTML'			 	 },
		'html2Canvas'			: { 'exports' : 'html2Canvas' 	 },
		'pdfmake'					: { 'exports' : 'pdfmake'				 },
		'vfs_fonts'				: { 'exports' : 'vfs_fonts'			 },
		'pdf'							: { 'exports' : 'pdf'						 },
		'sizing'					: { 'exports' : 'sizing'			 	 },
		'canvasContext'		: { 'exports' : 'canvasContext'	 },
		'format'					: { 'exports' : 'format' 			 	 },
		'tooltip'					: { 'exports' : 'tooltip' 		 	 },
		'loading'					: { 'exports' : 'loading' 		 	 },
		'legend'					: { 'exports' : 'legend' 			 	 },
		'sortHandler'			: { 'exports' : 'sortHandler'	 	 },
		'mouseHandler'		: { 'exports' : 'mouseHandler' 	 },
		'title'						: { 'exports' : 'title'				 	 },
		'comutation'			: { 'exports' : 'comutation'	 	 },
		'mutation'				: { 'exports' : 'mutation'		 	 },
		'patient'					: { 'exports' : 'patient'			 	 },
		'sample'					: { 'exports' : 'sample'			 	 },
		'group'						: { 'exports' : 'group'				 	 },
		'gene'						: { 'exports' : 'gene'				 	 },
		'scale'						: { 'exports' : 'scale'				 	 },
		'pq'							: { 'exports' : 'pq'					 	 },
		'needle'					: { 'exports' : 'needle'			 	 },
		'navi'						: { 'exports' : 'navi'				 	 },
		'needleplot'			: { 'exports' : 'needleplot'	 	 },
		'navigator'				: { 'exports' : 'navigator'			 },
		'pathway'					: { 'exports' : 'pathway'			 	 },
		'expressions'			: { 'exports' : 'expressions'	 	 },
		'expressionPlot'	: { 'exports' : 'expressionPlot' },
		'waterfall'				: { 'exports' : 'waterfall'    	 },
		'scatter' 				: { 'exports' : 'scatter'			 	 },
		'heatmap'					: { 'exports' : 'heatmap' 		 	 },
		'options'					: { 'exports' : 'options'			 	 },
	}
});